# Generated by Django 5.0 on 2025-12-10 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=10,
                    ),
                ),
                ("constraints", models.TextField(blank=True)),
                ("examples", models.JSONField(blank=True, default=list)),
                ("patterns", models.JSONField(blank=True, default=list)),
                (
                    "leetcode_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("leetcode_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "problems",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="problems_slug_fa7e51_idx"),
                    models.Index(
                        fields=["difficulty"], name="problems_difficu_cbb392_idx"
                    ),
                    models.Index(
                        fields=["leetcode_id"], name="problems_leetcod_bece08_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("c", "C"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                        ],
                        default="python",
                        max_length=20,
                    ),
                ),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("memory", models.IntegerField(blank=True, null=True)),
                ("is_solved", models.BooleanField(default=False)),
                ("is_accepted", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("test_cases_passed", models.IntegerField(default=0)),
                ("test_cases_total", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
