# Generated by Django 5.0 on 2025-12-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("problems", models.JSONField(default=list)),
                ("srs_problems", models.JSONField(default=list)),
                ("new_problems", models.JSONField(default=list)),
                ("completed_problems", models.JSONField(default=list)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "daily_plans",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SRSReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repetitions", models.IntegerField(default=0)),
                ("ease_factor", models.FloatField(default=2.5)),
                ("interval_days", models.IntegerField(default=1)),
                ("next_review", models.DateTimeField(blank=True, null=True)),
                ("last_review", models.DateTimeField(blank=True, null=True)),
                (
                    "last_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Again - Hard"),
                            (2, "Hard"),
                            (3, "Good"),
                            (4, "Easy"),
                            (5, "Perfect"),
                        ],
                        null=True,
                    ),
                ),
                ("total_reviews", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "srs_reviews",
                "ordering": ["next_review"],
            },
        ),
    ]
