# Generated by Django 5.0 on 2025-12-10 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("problems", "0002_initial"),
        ("srs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_plans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="srsreview",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="srs_review",
                to="problems.submission",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyplan",
            index=models.Index(
                fields=["user", "date"], name="daily_plans_user_id_b6f0fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyplan",
            index=models.Index(fields=["date"], name="daily_plans_date_ec20b1_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailyplan",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="srsreview",
            index=models.Index(
                fields=["next_review"], name="srs_reviews_next_re_d3c5f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="srsreview",
            index=models.Index(
                fields=["submission"], name="srs_reviews_submiss_c306bf_idx"
            ),
        ),
    ]
