# Generated by Django 5.0 on 2025-12-10 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("coach", "0001_initial"),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachinteraction",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_interactions",
                to="problems.submission",
            ),
        ),
    ]
