# Generated by Django 5.0 on 2025-12-10 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("coach", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coachinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="coachinteraction",
            index=models.Index(
                fields=["user", "created_at"], name="coach_inter_user_id_925e18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coachinteraction",
            index=models.Index(
                fields=["submission"], name="coach_inter_submiss_3630ac_idx"
            ),
        ),
    ]
