# Generated by Django 5.0 on 2025-12-10 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aihint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_hints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="aihint",
            index=models.Index(
                fields=["user", "problem_id"], name="ai_hints_user_id_e7238e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aihint",
            index=models.Index(
                fields=["created_at"], name="ai_hints_created_cefb00_idx"
            ),
        ),
    ]
